GET http://localhost:3001/api/test

###

GET http://localhost:3001/api/joke

###


POST http://localhost:3001/api/comedians
Content-Type: "application/json"

{
    "id": 0,
    "name": "Kevin Hart",
}

###

GET http://localhost:3001/comedians

###

POST http://localhost:3001/comedians
Content-Type: "application/json"

{
    "name": "Dave chappelle",
    "age": 29
}