GET http://localhost:3001/api/test

###

GET http://localhost:3001/api/joke

###

GET http://localhost:3001/api/comedians

###

POST http://localhost:3001/api/comedians
Content-Type: application/json

{
    "name": "Bert Smith",
    "age": 32
}